
enum Ev3SensorType {
    Button, Touch, Color, Ultrasonic, Gyro, IR
};

struct Ev3SensorEvent
{
    Ev3SensorType sensor_type;
};

enum Ev3Button {
    Back, Left, Right, Up, Down, Enter
};

struct Ev3ButtonEvent : Ev3SensorEvent
{
    //true if pressed, false if released
    boolean pressed;
    Ev3Button button;
};

enum Ev3MoveType {
    Forward, ForwardLeft, ForwardRight, SpinLeft, SpinRight, Backward
};

struct Ev3MoveCommand {
    Ev3MoveType move;
    boolean make;         //stop if false
};
